/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_zsy_hellogles_GLES2JNILib */

#ifndef _Included_com_example_zsy_hellogles_GLES2JNILib
#define _Included_com_example_zsy_hellogles_GLES2JNILib
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_zsy_hellogles_GLES2JNILib
 * Method:    onNDKSurfaceCreated
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_example_zsy_hellogles_GLES2JNILib_onNDKSurfaceCreated
  (JNIEnv *, jclass);

/*
 * Class:     com_example_zsy_hellogles_GLES2JNILib
 * Method:    onNDKSurfaceChanged
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_com_example_zsy_hellogles_GLES2JNILib_onNDKSurfaceChanged
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     com_example_zsy_hellogles_GLES2JNILib
 * Method:    onNDKDrawFrame
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_example_zsy_hellogles_GLES2JNILib_onNDKDrawFrame
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
